---
- hosts: rhv-m.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: Development
    cluster_name: Development_Cluster
    cluster_description: Development Cluster

  tasks:


    - name: Gather iSCSI Facts
      ovirt_host_storage_facts:
        auth: "{{ ovirt_auth }}"
        host: rhv-h-1
        iscsi:
         target: iqn.2019-08.com.example:deviscsivm
         address: 192.0.3.50
      register: dev_results

    - name: Setup iSCSI Storage Facts
      set_fact:
        lun_id: "{{ ovirt_host_storages | map(attribute='id') | list }}"

    - name: output of LUN ID
      debug:
         var: lun_id

    - name: Setup iSCSI Storage
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        host: rhv-h-1
        iscsi:
          target: iqn.2019-08.com.example:deviscsivm
          lun_id: "{{ lun_id }}"
          address: 192.0.3.50
        name: Dev_iSCSI_Data
        comment: Development DataCenter VM Storage
        description: Development DataCenter iSCSI Storage
        domain_function: data
        state: present
        wipe_after_delete: no
        discard_after_delete: no

    - name: Setup NFS Storage Data Domain
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        host: rhel-h-1
        nfs:
         address: 192.0.3.50
         path: /VM_Export/DEV_NFS/data
         version: v4
        name: Dev_NFS_Data
        domain_function: data
        comment: Development DataCenter NFS Data Domain
        description: Development DataCenter NFS Data
        state: present
        wipe_after_delete: no

    - name: Setup NFS Storage ISO Domain
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        host: rhel-h-1
        nfs:
         address: 192.0.3.50
         path: /VM_Export/DEV_NFS/iso
         version: v4
        name: Dev_ISO_Data
        domain_function: iso
        comment: Development DataCenter NFS ISO Domain
        description: Development DataCenter ISO Data
        state: present

    - name: Setup NFS Storage Export Domain
      ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ data_center_name }}"
        host: rhel-h-1
        nfs:
         address: 192.0.3.50
         path: /VM_Export/DEV_NFS/export
         version: v4
        name: Dev_EXPORT_Data
        domain_function: export
        comment: Development DataCenter NFS Export Domain
        description: Development DataCenter Export Data
        state: present

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
